-- Create comments table in Supabase PostgreSQL
CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_title TEXT NOT NULL,
  username TEXT NOT NULL,
  email TEXT NOT NULL,
  avatar_url TEXT,
  provider TEXT DEFAULT 'email',
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS (Row Level Security) if appropriate, or disable for public write/read
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

-- Allow public read access to comments
CREATE POLICY "Allow public read access to comments" ON comments
  FOR SELECT TO public USING (true);

-- Allow public insert access to comments
CREATE POLICY "Allow public insert access to comments" ON comments
  FOR INSERT TO public WITH CHECK (true);

-- Create index on post_title for optimized loading
CREATE INDEX IF NOT EXISTS idx_comments_post_title ON comments (post_title);
