-- Create subscribers table
CREATE TABLE IF NOT EXISTS subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  name TEXT,
  provider TEXT DEFAULT 'email',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE subscribers ENABLE ROW LEVEL SECURITY;

-- The Vercel serverless functions access this table using the SUPABASE_SERVICE_ROLE_KEY,
-- which bypasses RLS. Therefore, we block direct public access to secure the table.
DROP POLICY IF EXISTS "Deny public access to subscribers" ON subscribers;
CREATE POLICY "Deny public access to subscribers" ON subscribers
  FOR ALL USING (false) WITH CHECK (false);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_subscribers_email ON subscribers(email);
